apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocolors-app
spec:
  replicas: 1
  template:
    spec:
      containers:        
        - name: argocolors-app
          image: docker.io/argoproj/rollouts-demo:red
